sudo: required

services:
  - docker

before_install:
  - docker build -t kartheek/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true kartheek/react-test npm test -- --coverage


after_success:
  - docker build -t kartheek/multi-client ./client
  - docker build -t kartheek/multi-nginx ./nginx
  - docker build -t kartheek/multi-server ./server
  - docker build -t kartheek/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kartheek/multi-client
  - docker push kartheek/multi-nginx
  - docker push kartheek/multi-server
  - docker push kartheek/multi-worker
